### ISSUE TITLE
error: accepts 1 arg(s), received 2

### ISSUE THREAD

**Issue by ghost** [ublue-os/bootc-image-builder-action#11]
Here is a logs archive of a run that had this error:

[logs_33944558505.zip](https://github.com/user-attachments/files/18664572/logs_33944558505.zip)

Commit 2b0f3d8334d06a7e6ebb31ff6ff480bf359d2cc6 seems to be causing this.

I didn't set the `use-librepo` variable.

**Comment by p5** [comment]
Unfortunately the Bootc Image Builder image provided by osbuild (https://quay.io/centos-bootc/bootc-image-builder) has not been updated in a few weeks, so doesn't contain the --use-librepo flag.  

For the time being, we recommend you use our version of the image until they start pushing new ones.  For example:

```
      - name: Build ISO
        id: build
        uses: ublue-os/bootc-image-builder-action@main
        with:
          bootc-image-builder-image: ghcr.io/centos-workstation/bootc-image-builder:latest
          use-librepo: true
          config-file: ./image-builder-iso.config.toml
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
```

The osbuild team is aware and investigating why the images are not being pushed.
